In [ ]:
# This website is scrapeable for monthly temperatures, humidity, and pressure
url = https://www.timeanddate.com/weather/@1267254/historic?month=4&year=2024

In [41]:
from scipy.io import netcdf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import xarray as xr
import pygrib
#import eccodes
#import cfgrib

In [26]:
from scipy.io import netcdf_file
np.unique(netcdf_file('nc_files/'+'RF25_ind2022_rfp25.nc','r').variables['RAINFALL'][:], return_counts=True)

/Users/zacharymeurer/opt/anaconda3/lib/python3.9/site-packages/scipy/io/_netcdf.py:304: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  warnings.warn((


(array([-9.99000000e+02,  0.00000000e+00,  1.00000001e-01, ...,
         9.19281799e+02,  9.21060242e+02,  9.79144775e+02]),
 array([4544615, 1277564,      19, ...,       1,       1,       1]))

In [27]:
# data from https://www.imdpune.gov.in/cmpg/Griddata/Rainfall_25_NetCDF.html
rf2022 = netcdf_file('nc_files/RF25_ind2022_rfp25.nc','r').variables['RAINFALL'][:]

In [28]:
rf2022.shape

(365, 129, 135)

In [29]:
rf2022

array([[[-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        ...,
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.]],

       [[-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        ...,
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.]],

       [[-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -999., -999.],
        ...,
        [-999., -999., -999., ..., -999., -999., -999.],
        [-999., -999., -999., ..., -999., -99

In [ ]:
for i in range(2014)

In [17]:
file2read = netcdf.NetCDFFile('nc_files/'+'RF25_ind2022_rfp25.nc','r')
#temp = file2read.variables['U'] # var can be 'Theta', 'S', 'V', 'U' etc..
#data = temp[:]*1
#file2read.close()
rainfall = file2read.variables['RAINFALL']

/var/folders/g7/1_kwfbnd73qfqrms900t1n040000gn/T/ipykernel_2932/668660447.py:1: DeprecationWarning: Please use `NetCDFFile` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.
  file2read = netcdf.NetCDFFile('nc_files/'+'RF25_ind2022_rfp25.nc','r')
/Users/zacharymeurer/opt/anaconda3/lib/python3.9/site-packages/scipy/io/_netcdf.py:304: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  warnings.warn((


In [31]:
!pip install pygrib==2.0.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 9.7 MB/s eta 0:00:00:00:0100:01
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/g7/1_kwfbnd73qfqrms900t1n040000gn/T/pip-install-u6hb3zxp/pygrib_06c71a394796406b806644b93cfc9e6a/setup.py", line 18, in <module>
          import pyproj
      ModuleNotFoundError: No module named 'pyproj'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/g7/1_kwfbnd73qfqrms900t1n040000gn/T/pip-install-u6hb3zxp/pygrib_06c71a394796406b806644b93cfc9e6a/setup.py", line 21, in <module>
          from mpl_toolkits.basemap import pyproj
      ModuleNotFoundError: No module named 'mpl_toolkits.basemap'
      
      During handling of the a

In [71]:
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import mpl_toolkits
#from mpl_toolkits.basemap import Basemap
mpl_toolkits.basemap.Basemap()

AttributeError: module 'mpl_toolkits' has no attribute 'basemap'

In [43]:
grbs = pygrib.open("ERA5-Land/adaptor.mars.internal-1717433307.8303945-4823-1-5f80d3ef-530c-474e-8510-ff88a56fdd46.grib")
grb = grbs.select()[0]
data = grb.values

In [89]:
grb['longitudeOfFirstGridPointInDegrees']

74.6

In [88]:
plt.figure(figsize=(12,8))

print(grbs.select()[3])
print(grbs.select()[3].values.shape)

4:Skin reservoir content:m of water equivalent (instant):regular_ll:surface:level 0:fcst time 0 hrs:from 201401011200
(43, 27)


<Figure size 1200x800 with 0 Axes>

In [63]:
xr.load_dataset("ERA5-Land/adaptor.mars.internal-1717433307.8303945-4823-1-5f80d3ef-530c-474e-8510-ff88a56fdd46.grib",engine='cfgrib')

ValueError: found the following matches with the input file in xarray's IO backends: ['cfgrib']. But their dependencies may not be installed, see:
http://xarray.pydata.org/en/stable/user-guide/io.html 
http://xarray.pydata.org/en/stable/getting-started-guide/installing.html